root: true

env:
  node: true
  jest: true
  browser: true

extends:
  - "airbnb-base"

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  linebreak-style: 0
  no-param-reassign: 0
